# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-03 18:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile_pic', models.ImageField(upload_to='photos/')),
                ('User_bio', models.CharField(max_length=300)),
                ('Address', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('Landingpage_img', models.ImageField(upload_to='photos/')),
                ('Description', models.CharField(max_length=300)),
                ('Livelink', models.CharField(max_length=100)),
                ('Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Design', models.DecimalField(decimal_places=1, max_digits=2)),
                ('Usability', models.DecimalField(decimal_places=1, max_digits=2)),
                ('Content', models.DecimalField(decimal_places=1, max_digits=2)),
                ('Score', models.DecimalField(decimal_places=1, max_digits=2)),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
