# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-04 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190804_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='Content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='Design',
            new_name='design',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='Project',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='Score',
            new_name='score',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='Usability',
            new_name='usability',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='User',
            new_name='user',
        ),
    ]
